explicit_timeout=15
auto_screenshot=true
url=https://www.saucedemo.com/inventory.html
selenium_url=http://localhost:4444/wd/hub
browser=chrome
proxy_host=host.docker.internal
proxy_port=9090
proxy_protocols=http,https
proxy_type=MANUAL
no_proxy=localhost,127.0.0.1